version: '2.1'
services:
  backend:
    restart: always
    build: ./backend
    env_file:
      - db.env.secrets
      - aws.env.secrets
      - app.env.secrets
    environment:
      - ENVIRONMENT=dev
      - POSTGRES_PORT_5432_TCP_ADDR=db
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:latest
    env_file: db.env.secrets
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    expose:
      - "5432"

volumes:
  postgres-data:
    driver: local
