version: '3'
services:
    test:
      build: ./backend
      command: make test
      environment:
        - ENVIRONMENT=docker
        - POSTGRES_PORT_5432_TCP_ADDR=test_db
      depends_on:
        - test_db

    test_db:
      image: postgres:latest
      volumes:
        - test-postgres-data:/var/lib/postgresql
      expose:
        - "5432"
      environment:
        - POSTGRES_USER=insuratech-test
        - POSTGRES_PASSWORD=insuratech

volumes:
    test-postgres-data:
      driver: local
